### ISSUE TITLE
Widow location on low resolution displays

### ISSUE THREAD

**Issue by kernelpanic95** [kdesantis/AdminLauncher#23]
Window appears at the top right corner at startup when the display resolution is set at 1024x768.
I'm unable to use top menus as you can see in the screenshot attached.
![Cattura](https://github.com/user-attachments/assets/91dabb98-6db1-439e-9c80-2eed9cfd7710)

**Comment by kdesantis** [comment]
The solution is: change monitors! 🤣 I'm joke , i have a solution
